apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fleetops-eks-cluster
  region: us-east-1
  version: "1.32"

iam:
  withOIDC: true # Enables IAM Roles for Service Accounts (IRSA)

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver # Enables EBS PersistentVolumes (gp3) for DB & Prometheus

managedNodeGroups:
  - name: fleetops-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 30
    volumeType: gp3
    amiFamily: AmazonLinux2023
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true
        ebs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
