apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fleetops-eks-cluster
  region: us-east-1
  version: "1.30"

iam:
  withOIDC: true # Required for AWS Load Balancer Controller and IRSA

managedNodeGroups:
  - name: fleetops-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 30
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
